### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by JonahKayizzi** [JonahKayizzi/Doctors-Reservations-Backend#12]
The tasks for this project have been evenly distributed amongst the following 4 individuals;

@JonahKayizzi 
@asdt560 
@Camilovelag 
@cvalencia1991 

Here is the [link](https://github.com/users/JonahKayizzi/projects/7/views/1) to the project
Here is the [link](https://github.com/JonahKayizzi/Doctors-Reservations-Frontend) to the front end repository
![image](https://user-images.githubusercontent.com/11190489/220763245-b23c4a4a-ebdc-4f5e-9d22-d570dd1c6a09.png)

**Comment by Meltrust** [comment]
Hi @JonahKayizzi,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All tasks have been pointed, and assigned in a fair way✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
